asn: 65000

bgp_neighbors:
  - { remote_as: 65000, neighbor: 10.1.1.101, update_source: Loopback0 }
  - { remote_as: 65000, neighbor: 10.1.1.102, update_source: Loopback0 }

L2VNI:
  - { vlan_id: 140, vni: 50140, ip_add: 172.21.140.1/24, vlan_name: L2-VNI-140-Tenant1, mcast: 239.0.0.140 }
  - { vlan_id: 141, vni: 50141, ip_add: 172.21.141.1/24, vlan_name: L2-VNI-141-Tenant1, mcast: 239.0.0.141 }

L3VNI:
  - { vlan_id: 999, vlan_name: L3-VNI-999-Tenant1, vni: 50999 }
