---

- name: Configuring Leaf Switches
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: spines
  tasks:
    - name: Configure BGP EVPN
      nxos_bgp_af:
       asn: "{{ asn }}"
       afi: l2vpn
       safi: evpn
      tags: evpn
    - name: Configure iBGP neighbor EVPN AF
      nxos_bgp_neighbor_af:
       asn: "{{ asn }}"
       neighbor: "{{ item.neighbor }}"
       afi: l2vpn
       safi: evpn
       route_reflector_client: "true"
       send_community: both
      with_items: "{{ bgp_neighbors }}"
      tags: evpn
