loopback0: 10.1.1.3/32
loopback1: 10.1.1.113/32
router_id: 10.1.1.3
eth1: 10.1.10.17/30
eth2: 10.1.10.21/30
access_vlan: 141

L3_interfaces:
- { interface: Ethernet1/1, descr: Underlay_dc1-spine-001_Ethernet1/3 }
- { interface: Ethernet1/2, descr: Underlay_dc1-spine-002_Ethernet1/3 }

L3_loopbacks:
- { interface: loopback0, descr: RID and Update Source }
- { interface: loopback1, descr: Anycast RP }

Underlay_interfaces:
  - { underlay_int: Ethernet1/1, underlay_addr: 10.1.10.17/30, underlay_descr: Underlay_dc1-spine-001_Ethernet1/3 }
  - { underlay_int: Ethernet1/2, underlay_addr: 10.1.10.21/30, underlay_descr: Underlay_dc1-spine-002_Ethernet1/3 }

Lag_interfaces:
  - { lag_name: port-channel1, lag_member: Ethernet1/3, lag_mode: active}

rp_address: 10.1.1.200
s1_loopback: 10.1.1.101
s2_loopback: 10.1.1.102
