loopback0: 10.1.1.2/32
loopback1: 10.1.1.112/32
router_id: 10.1.1.2
eth1: 10.1.10.9/30
eth2: 10.1.10.13/30
access_vlan: 140

L3_interfaces:
- { interface: Ethernet1/1, descr: Underlay_dc1-spine-001_Ethernet1/2 }
- { interface: Ethernet1/2, descr: Underlay_dc1-spine-002_Ethernet1/2 }

L3_loopbacks:
- { interface: loopback0, descr: RID and Update Source }
- { interface: loopback1, descr: Anycast RP }

Underlay_interfaces:
  - { underlay_int: Ethernet1/1, underlay_addr: 10.1.10.9/30, underlay_descr: Underlay_dc1-spine-001_Ethernet1/2 }
  - { underlay_int: Ethernet1/2, underlay_addr: 10.1.10.13/30, underlay_descr: Underlay_dc1-spine-002_Ethernet1/2 }

Lag_interfaces:
  - { lag_name: port-channel1, lag_member: Ethernet1/3, lag_mode: active}

rp_address: 10.1.1.200
s1_loopback: 10.1.1.101
s2_loopback: 10.1.1.102
